"""Add course code and duration to exam sessions and qp submissions

Revision ID: 35c89704323f
Revises: cab2fbdd18a1
Create Date: 2026-05-19 16:23:33.516722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c89704323f'
down_revision: Union[str, Sequence[str], None] = 'cab2fbdd18a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('course_code', sa.String(), nullable=True))
    op.add_column('exam_sessions', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('qp_submissions', sa.Column('course_code', sa.String(), nullable=True))
    op.add_column('qp_submissions', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qp_submissions', 'duration')
    op.drop_column('qp_submissions', 'course_code')
    op.drop_column('exam_sessions', 'duration')
    op.drop_column('exam_sessions', 'course_code')
    # ### end Alembic commands ###
