"""Add department and semester to Course

Revision ID: d1deef889233
Revises: e2c3f8d1ef18
Create Date: 2026-05-19 17:15:08.164156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1deef889233'
down_revision: Union[str, Sequence[str], None] = 'e2c3f8d1ef18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('department', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('semester', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'semester')
    op.drop_column('courses', 'department')
    # ### end Alembic commands ###
